/**
 * Doraemon hero portrait, 50×72.
 *
 * Pixelated from a screenshot of Doraemon rather than drawn by hand. An earlier
 * hand-drawn attempt got the head and eye proportions wrong and did not read as
 * the character at all. Sampling real artwork guarantees the silhouette is
 * right, which is the entire reason to use pixel art of a known subject.
 *
 * The source is a close-up with a second, translucent Doraemon behind the main
 * one and flat background bands at the edges. The crop takes the main figure —
 * the one with the white face, red collar and bell — and stops short of the
 * background bands, which otherwise show up as grey slivers that look like
 * rendering faults rather than artwork.
 *
 * Colours are FIXED, not theme-aware. A character's colours do not change with
 * the reader's theme, and mapping him onto the theme-aware `ink`/`surface`
 * characters would turn his face dark in dark mode. The letter run A–J/L is
 * deliberately clear of the site palette's characters for that reason.
 *
 * One deliberate hand edit on top of the sample: the left edge carries 8 columns
 * where a sliver of the translucent Doraemon behind was painted over with the
 * surrounding head blue. At 72 cells wide that sliver read as a rendering fault.
 *
 * Legend: A=outline B=blue C=blue shade D=blue highlight E=white F=white shade
 *         G=red H=red shade I=yellow J=yellow shade  L=grey  .=transparent
 */
export const DORAEMON = [
  "BBBBBBCCCBBBBBBBBBBCCCCCCCCCCBDDDDDDDDDDDDDDDDDDDDDDDDBCBDDDDDDDDDDDDCCD",
  "CBBBBBCCCCBBBBBBBBBCCCCCCCCCCBDDDDDDDDDDDDDDDDDDDDDDDDDDBCCBBDDDDBBCCBDD",
  "CCBBBBBBBBBBBBBBBBBCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBCCCCBBDDDDD",
  "CCBBBBBBBBBBBBBBCBBCCCCCCCBCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
  "CBBBBBBBBBBBBBBBCCCCCCCCCCBCCCBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
  "BBBBBBBBBBBBBBBBCCCCCCCCCBBCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
  "BBBBBBBBBBBBBBBBBCCCCCCCCCBCCCCBDDDDDDDDDDDDFFFFDDDDDDBDDFFFDDDDDDDDDDDD",
  "BBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCDDDDDDDDBDFEEEEEEFLDDBDFEEEEFDBDDDDDDDDD",
  "BBBBBBBBBBBBBBBBBCCCCCCCCCCCCCCCBDDDDDDBDFEEEEEEEEFLBLFEEEEEEFDBDDDDDDDD",
  "CCCCBBBBBBBBBBBBCCCCCCCCCCCCCCCCCBDDDDDDFEEEEEEEEEEDLFFEEEEEEEFLDDDDDDDD",
  "CCCCBBBBBBBBBBBCBCCCCCCCCCCCCCCCCCBDDDDFEEEEEEEEEEEFLFEEEEEEEEEFBDDDDDDD",
  "CCCCBBBBBBBBBBBCCBBCCCCCCCCCCCCCCCCBDBDFEEEEEEEEEEEFLFEEEEEEEEEFDDDDDDFF",
  "CCCCBBBBBBBBBBCCCBBBBCCCCCCCCCCCCCCCBLFEEEEEEEEEEEFLLLFEEEEEEEEFFFFFFFFF",
  "CCCCCBBBBBBBBCCCCBBBBCCCCCCCCCCCCLLLDDFEEEEEEEEEFLLLFFLLFEEEEEEFFEEEEEEE",
  "CCCCCCCCCCCCBCCCBBCCCCCCCCCLLLDFFFFFFFFEEEEEEEFLLFFLFEFFLLEEEEEFFEEEEEEE",
  "CCCCCCCCCCCCCCCCCCCCCCCLLDFFFFEEEEEEFFFEEEFFLLLFFEELFEEEFFLLFEFFFEEEEEEE",
  "CCCCCCCCCCCCCCCCCCCCLLFFFEEEEEEEEEEEFFFFLLLLFEEEEEFLFEEEEEFFLLLLEEEEEEEE",
  "CCCCCCCCCCCCCCCCCLLFEEEEEEEEEEEEEEEEELLFFEEEEEEEEEFLFEEEEEEEEEFFEEEEEEEE",
  "CCCCCCCCCCCCCCLLFEEEEEEEEEEEEEEEEEEEEFFEEEEEEEEFLLFFFLFEEEEEEFLEEEEEEEEE",
  "CCCCCCCCCCCCLLEEEEEEEEEEEEEEEEEEEEEEEEFFEEEEEEFLAALLAAAFEEEEFFFEEEEEEEEE",
  "CCCCCCCCCCCDFEEEEEEEEEEEEEEEEEEEEEEEEEFFFFEEEEFAAHHHHHAFEEFFFFEEEEEEEFFF",
  "CCCCCCCCCDFEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFFLHGGHHHHLFFFFFEEEEFFFFFDD",
  "CCCCCCCBFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFHGFFGHHHAFFFEEEEEEFFBFFFE",
  "DCCCCCCFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFHGFEGHHHLFEEEEEEEEFFEEEEE",
  "FCCCCCFEEEEEEEEEEEEEEEEEFFFFFFEEEEEEEEEEEEEEEEFLGFFGHHHLFEEEEEEEEEEEEEEE",
  "FDCCCCEEEEEEEEFFFFFFFFFFFFFFFFEEEEEEEEEEEEEEEEEFHHGHHHLFEEEEEEEEEEEEEEEE",
  "DDCCCDEFFFFFFFFFFFFFFFFFFFFFFFEEEEEEEEEEEEEEEEEFFLGHGLFEEEEEEEEEEFFFFFFE",
  "CCCCCCFFFFFFFFFFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFEEEEEEEEEEFFFFFFFF",
  "CCCCCCFFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFEEEEEEEEEEEEEFFFFFFF",
  "CCCCCCFEEEEEEEEEEEEEEEEEEEEEEFEEEEEEEEEEEEEEEEEEEEFFEEEEEEEEEEEEEEEEEEEE",
  "CCCCCCDEEEEEEEEEEEEEEEEEEFFLLFEEEEEEEEEEEEEEEEEEEEFFEEEEEEEEEEEEEEEEEEEE",
  "CCCCCCCDEEEEEEEEEEEEEFFLLLFFFFEEEEEEEEEEEEEEEEEEEELFEEEEEEEEEEEEEEEEEEEE",
  "CCCCCCCCDEEEEEEEEEFLLLFFFEEEEEEEEEEEEEEEEEEEEEEEEFFFEEEEEEEEEEEFDDFFEEEE",
  "CCCCCCCCCLFEEEFFLLFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFEEEEEEEEEEEEEEFFCCCCF",
  "CCCCCCCCCCLFFLLFEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFEEEEEEEEEEEEEEEEEEEFF",
  "CCCCCCCCCCAADFEEEEEEEEEEEEEFFFLFEEEEEEEEEEEEEEEEFFFEEEEEEEEEEEEEEEEEEEFF",
  "CCCCCCCCCCCCLDFEEEEEEEEEFFFLLFFEEEEEEEEEEEEEEEEEFFFEEEEEEEEEEEEEEEEEEFDD",
  "CCCCCCCCCCCCCCLFFEEEEFFFFLFFEEEEEEEEEEEEEEEEEEEEFLEEEEEEEEEEEEEEEEEFFCCC",
  "CCCCCCCCCCCCCCCCLFFFFFLLFEEEEEEEEEEEEEEEEEEEEEEFFFEEEEEEEEEEEEEEEFFCCCCC",
  "CCCCCCCCCCCCCCCCCLLLLFFEEEEEEEEEEEEEEEEEEEEEEEFFLFFEEEEEEEEEEEFFFCCCCCCC",
  "CCCCCCCCCCCCCCCCCCCCLLFFFEEEEEEEEEEEEEEEEEEEEFFFFLFFEEEEEEEFFFDLCCCCDDDD",
  "CCCCCCCCCCCCCCCCCCCCCCCLLFFFEEEEEEEEEEEEEEEEFFFEEFFFEEEFFFDDLCCCCCCCCCCC",
  "CCCCCCCCCCCCCCCCCCCCCCCCAALLLFFFFEEEEEEEEEEEEEEEEEFFFFLLBCCCCCCCCCCCCCCC",
  "CCCCCCCCCCCCCCCCCCCCCCCCCCCLAHHLLLLFFFFFFFFFFFFLLLLLFFLCCCCCCCCCCCCCCCCC",
  "CCCCCCCCCBCCCCCCCCCCCCCCCCCCLFLHHHHHLLLLJJJJLLLHHLLFFLCCCCCCCCCCCCCCCCCC",
  "CCBCCCCCCBBBCCBBCCCCCCCCCCCCDEFFFLLLHJJJHHHHHHHLFFFEFCCCCCCCCCCCCCCCCCCC",
  "CCBBCCCCCCBBBBBCCCCCCCCCCCCCFEEEEFFLJJJJJJJJJJHLEEEELCCCCCCCCCCCCCCCCCCC",
  "CCBBBBCCCCBBBCCCCCCCCCCCCCCCDEEEEEEFJJJJJJAJIIILEEEFCCCCCCCCCCCCCCCCCCCC",
  "CCBBBBCCCCCBBCCCCCCCBBCCCCCCLEEEEEEFJIIIIAAJIIILEEELCCCCCCCCCCCCCCCCCCCC",
  "CCCBBBCCCCCBCCBCCCCBBBCCCCCCCFEEEEEFLIIIIJAIIILFEEFBCCCCCCCCCCCCCCCCCCII",
] as const;
